# Capstone 2 Project: EmporiUm Sales Analysis

The two territories I have been assigned to analyze are South Carolina and Texas, they reside in the South Region.

In [85]:
# importing libraries needed for analysis

import numpy as np # fast numerical calculations
import pandas as pd # used for working with DataFrames (tables)
import matplotlib.pyplot as plt # creates visualization and charts

## Loading in CSV Files One-by-One

In [87]:
# file 1:
store_sales = pd.read_csv("StoreSales.csv") # loading in StoreSales data

store_sales.info() # confirming all contents were imported

store_sales.head() #previewing table (top 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [88]:
# file 2:
store_detail = pd.read_csv("StoreDetail.csv") # loading in StoreDetail data

store_detail.info() # confirming all contents were imported

store_detail.head() # previewing table (top 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [89]:
# file 3:
products = pd.read_csv("Products.csv") # loading in Products data

products.info() # confirming all contents were imported

products.head() # previewing table (top 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [90]:
# file 4
product_categories = pd.read_csv("ProductCategories.csv") # loading in ProductCategories data

product_categories.info() # confirming all contents were imported

product_categories.head() # previewing table (top 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [91]:
# file 5
customer_list = pd.read_csv("customer_list.csv") # loading in customer_list data

customer_list.info() # confirming all contents were imported

customer_list.head() # previewing table (top 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

## Core Marketing Analysis

### Territory Managers, Store IDs, and Cities

In [115]:
# filtering store_detail DataFrame (South Carolina & Texas)

territory_stores = store_detail[(store_detail['State'] == 'South Carolina')| # keeping SC stores
                                 (store_detail['State'] == 'Texas')] # keeping TX stores
                                 
# displaying store ID, city, state and manager
territory_stores[['Store ID', 'Store Location', 'State', 'Territory Manager']]

     Store ID Store Location           State      Territory Manager
98        852     Charleston  South Carolina             Len Jensen
99        853     Greenville  South Carolina             Len Jensen
100       901      Arlington           Texas  Jeff "Howdy" Richards
101       902         Austin           Texas  Jeff "Howdy" Richards
102       903        Bacliff           Texas  Jeff "Howdy" Richards
103       904        Baytown           Texas  Jeff "Howdy" Richards
104       905       Beaumont           Texas  Jeff "Howdy" Richards
105       906     Cedar Park           Texas  Jeff "Howdy" Richards
106       907         Dallas           Texas  Jeff "Howdy" Richards
107       908         Denton           Texas  Jeff "Howdy" Richards
108       909         Desoto           Texas  Jeff "Howdy" Richards
109       910     Fort Worth           Texas  Jeff "Howdy" Richards
110       911     Georgetown           Texas  Jeff "Howdy" Richards

### Monthly Total Revenue for In-Store Sales

In [126]:
# converting Transaction Date column (store_sales) to pandas datetime format
store_sales['Transaction Date'] = pd.to_datetime(store_sales['Transaction Date']) # making date usable

# creating a Month column from Transaction Date
store_sales['Month'] = store_sales['Transaction Date'].dt.to_period('M') # extracting year & month

# merging State columns from store_detail using Store ID
sales_w_state = store_sales.merge(store_detail[['Store ID', 'State']], # Store ID + State
                                  on = 'Store ID') # matching rows using Store ID

# filtering to keep SC and TX only
territory_sales = sales_w_state[(sales_w_state['State'] == 'South Carolina')| # SC stores
                                (sales_w_state['State'] == 'Texas')] # TX stores

# grouping States, Month & total Sale Amount
monthly_revenue = territory_sales.groupby(# grouping by state & month
    ['State','Month'])['Sale Amount'].sum().reset_index() # total revenue for each group, resetting them as regular columns
   
#displaying output
monthly_revenue

             State    Month  Sale Amount
0   South Carolina  2022-01      9640.38
1   South Carolina  2022-02      9763.98
2   South Carolina  2022-03      8366.63
3   South Carolina  2022-04      8929.63
4   South Carolina  2022-05      5396.03
..             ...      ...          ...
91           Texas  2025-08     98630.93
92           Texas  2025-09    109065.94
93           Texas  2025-10    168955.72
94           Texas  2025-11    105400.74
95           Texas  2025-12     95570.59

[96 rows x 3 columns]